utils/functions.go
Does not try to set the UID and GID if the current user is already the same as the one that is specified in the configuration.
=> Add a necessity check for uid/gid setting

README.md, app/app.go, cache/README.md, cache/cache_test.go, cache/interface.go, cache/lru/lru.go, cache/lru/lru_test.go, cache/lru/stats.go, cache/lru/stats_test.go, cache/new_cache_manager.go, cache/types.go, cache/types.go.template, handler/proxy/handler.go, storage/README.md, storage/disk/impl.go, storage/new.go, storage/types.go, storage/types.go.template, upstream/new_upstream.go, upstream/simple/impl.go, vhost/virtual_host.go
Mainly renaming types and methods. All the `thing.ThingStuff` has been eradicated from the code.
=> Refactoring removing stutter

storage/disk/impl.go, storage/disk/impl_test.go, storage/disk/testing_mocks.go
The storage uses a map to hold HTTP headers for all known files kept in the cache.
Previously this map was used without any protection between many goroutines. This lead to occasional crashes.
Also, I've removed some dot imports from the disk implememtation. Maybe it should have been in different commit, but hey!
=> There is a mutex which protects the storage headers map

app/init.go, logger/new.go, logger/new_loggers_test.go, storage/disk/impl_test.go, storage/new.go, storage/new_storages_test.go, types/virtual_host.go
This somewhat fixes #37. Also, it fixes a bug, similar to the one from yesterday. Previously, if a cache zone had multiple vhosts and each vhost had it's own custom logger, the logger of the first vhost also became the logger of the cache zone. 
After this fix, the cache zone logger is always the same as the default application logger. In the future we can easily either add the functionality to have custom loggers for each cache zone, or make the cache storage to always use the vhost's logger for each request it handles.
=> Simplify the initialization of the app and some modules.

app/env_test.go, handler/cache/old_test.go, storage/disk/impl_test.go, storage/disk/utils_test.go, utils/functions_test.go, utils/testutils/test_helpers.go
this is required because it imports "testing" which uses "flag" package
to work with cli arguments which are then leaked in nedomi's arguments.
=> move test_helpers in it's old package

.gitignore, main.go
An command line argument is added which can be used to set an
address on which the http/pprof listener will use. By default
no linstener is started.
=> Adds an option to start a pprof http listener

tools/logrotate.conf
The logrotate job upgrades nedomi when it rotates a log file. We should change this to reload signal when it is stable. Or maybe we can add an special signal for recreating the log files.
=> Adds a logrotate config for nedomi in the tools

config/config_test.go, config/section_http.go
This reverts commit 53123b677263f90a33c3ffb2c1f8ba9e8be10d60.
=> Revert "Add validation for duplicate cache zone+key settings" - fixes #105

storage/scheduler.go
time.After makes a new time.Timer which generates a small amount of garbage for the gc to collect. We can spare the gc the trouble and just reuse the a Timer
=> scheduler: reuse timer

handler/cache/bench_test.go, handler/cache/handler.go, handler/cache/handler_helpers.go, handler/cache/handler_test.go, handler/cache/old_test.go, handler/cache/specifics_test.go
Up until now on 'too many open files' a new connection to the upstream
was opened which probably would fail as well.
This change does not try to make it less likely for 'too many open files'
to occur, but instead cuts short the request handling and returns an
InternalServerError where possible or just stop returning data if
already in the middle of a response.
=> cache.handler: return 500 on 'too many open files'

handler/headers/README.md, handler/headers/headers.go, handler/headers/headers_test.go
this had the small problem that added headers will be added twice. Given
the lack of evidince that the feature was needed and the impossibility
of implementing it well it is now removed.
=> handler.headers: don't rewrite response header before next

app/init_test.go, config/config_test.go, handler/status/status_page.go, utils/functions.go, utils/testutils/test_helpers.go
this was due to importing ./utils/testutils package in production code in order
to use ProjectPath, which is why it was moved in ./utils
=> fix import of 'testing' in production code

handler/proxy/new.go, types/request_handler.go
for handlers who do not call next (ever) it's unreasonable to have next
handler - it's most probably configuration error which may or may not be
fatal. For this reasons it should be prohibited.
=> add NotNilNextHandler error type and use it in handler.proxy

handler/cache/handler.go, handler/cache/handler_helpers.go
the rewritten headers when serving from the cache:
Date, Age, Cache-Control (with max-age), Expires
Now non of this would be cached as well as they are always recalculated.
=> handler.cache: rewrite some time/date headers - fixes #119

app/app.go, utils/netutils/timeout_conn.go, utils/netutils/timeout_listener.go
This is fun feature which circumvents the fact that http.Server timeout
is not useful when you have long living connections. If you have a
connection which will have to live for 20 minutes you can either put
your timeout to something above 20 minutes and possibly have connections
which are stale for 20 minutes, have timeout connections for no good
reason or do what is done through this commit.
This commit changes the meaning of net.Conn.Set*Deadline to mean
"calculate me a timeout from now till the deadline and than use that to
deadline each Read|Write operation for that timeout", not all of them.
This means that you can have a timeout of 10 seconds and connections
which have been used to transmit data for as long as each Read|Write
takes less than 10 seconds.
This is only done for the …
=> change http.Server.*Timeout to be on a per Read|Write basis

app/write_log.go, handler/cache/caching_proxy.go, handler/cache/handler.go, handler/cache/handler_helpers.go, handler/cache/part_writer.go, utils/httputils/flexible_response_writer.go, utils/netutils/timeout_conn.go, utils/readers.go, utils/readers_test.go, utils/writers.go
there a lot of changes to many of the io.Writer/io.Reader
implementations. All of them are more or less so that an io.Copy with a
io.Reader being *os.File and an io.Writer of net.Conn could be called at
some point.
Currently this is not possible with the throttle handler - which will
be implemented at a later time.
The same is true for the mp4 handler when a start parameter is provided.
This will be harder to fix and will need another change to the
github.com/MStoykov/mp4 library.
The flv handler was not tested.
The usage of sendfile ofcourse does not work if used on operating system
with no sendfile syscall or an alternative. Also it's only possible to
be done with os.File, so only disk cached or static content can be sent.
=> make it possible for sendfile to be used

app/app.go, handler/proxy/impl.go, handler/proxy/impl_test.go, handler/proxy/new.go, types/app_stats.go
add 'try_other_upstream_on_code' settings that maps returned status code
to upstream to be retried with. The retry is only on the first request.
=> handler proxy: implement #168

handler/proxy/impl.go
Previously, an upstream request was using a Host header
set by the dns resolver. This header was always ip:port. Such a behaviour
is not desirable in the situations where the upstream servers were
configured using a domain name.
=> Upstream request will use the original Host header

README.md, app/app.go, config/section_http.go, utils/netutils/task_pool.go, utils/netutils/timeout_conn.go, utils/netutils/timeout_listener.go
The amount of threads that will be reading/writing on incoming
connections (client once) is restricted. This is done by a basic worker
pool by default with NumCPU/2 workers. This can be changed by the new
io_workers setting in the HTTP section.
=> restrict the amount of HTTP io workers

utils/copy_n.go, utils/netutils/timeout_conn.go
timeoutConn.ReadFrom was way too complicated - now it's a lot simpler.
the new utils.CopyN makes certain that only one io.LimitedReader is
used. This is mostly useful incases where two or more such might get
added one after another leading to sendfile not being used - it can only
get trough one.
=> refactor timeoutConn

.travis.yml
it's also worth nothing that it didn't actually work but because we
weren't redirecting the error output we never found out :(
=> go lint is done in fmtpolice now

app/app.go, app/connections.go, app/net.go, app/net_test.go, contexts/connection.go, handler/throttle/throttle.go, types/incoming_connection.go, utils/netutils/timeout_conn.go, utils/throttle/min_max.go, utils/throttle/throttled_writer.go, utils/throttle/throttled_writer_bench_test.go, utils/throttle/throttled_writer_test.go, utils/throttle/timers.go, utils/throttle/timers_test.go
the throttle handler reimplementation has one main strenght - it can use
sendfile. Other benifits is that it removes a dependancy. I would also
argue it's lighter runtime(don't quote me).
In order to use this we use the now new ThrottledWriter which records
how much bytes it has throttled at a given speed and tries to write as
much as it can in order to get to the speed that is requested.
The reason why it's done in the timeoutConn instead of in the handler
given that it requires the whole getting the correct connection for each
request is:
http.ResponseWriter.ReadFrom does os.Stat on each io.LimitedReader it
gets. This adds up pretty quickly to hundred of thousands of os.Stat, which
both slow down the whole application, and make a lot of objects.
Given the fact that io.LimitedReader is …
=> reimplement throttle handler

README.md, app/app.go, app/reload.go, app/reload_test.go, config/section_http.go, utils/netutils/timeout_conn.go, utils/netutils/timeout_listener.go
the new min will be used when throttling, to prevent writing in very
small pieces, doing a lot of syscalls.
=> split io_transfer_size in min and max settings

Makefile
If you are building in a gitless directory the git commands will
fail. This may be because you are building from a source archive.
This commit gives you the option to supply the variables
manually via environment variables:
$ GIT_TAG="v0.1.2" make
This does not solve the problem completely since ideally,
you should be able to just type `make` and compile nedomi
without warnings.
=> Git vars can be overriden wint env vars

app/env.go
An unexpected white space in the PID file was causing an error
message on shutdown. Such an whitespace is easy to slip into
the file. For example `echo 123 > nedomi.pid` will add a
new line. Situations like this shouldn't be a cause for alarm.
=> Remove whitespaces while reading PID file contents

handler/dir/dir.go
this is mostly useful(and semi required) when the dir handler is used in
a location with a path different from `/` for example `/doc`.
Without it a request `/var/www/index.html` (with dir handler with `root`
`/var/www`) will try to serve file with path `/var/www/doc/index.html`.
To fix this the new `strip` setting was added. It will strip a provided
path from the beginning of the requested path.
Setting it to `/doc` in the above example will give the (expected)
result of serving `/var/www/index.html`.
=> handler.dir: gets `strip` setting
